# Base
########################################

# nom de l'utilisateur non privilégié
user: user

mdp:
  # mkpasswd -m sha512crypt -R 200000
  root: mettre hash

# clés publiques ssh
pubkeys:
  - mettre clés publique
  - mettre clés publique
  - mettre clés publique
