- name: Fichier alias
  copy:
    src: alias
    dest: /root/.alias

- name: Inclusion dans .bashrc
  blockinfile:
    path: /root/.bashrc
    marker: "# {mark} alias"
    block: |
      if [ -f ~/.alias ]; then
        . ~/.alias
      fi
