# https://towardsdatascience.com/set-up-of-a-personal-gpu-server-for-machine-learning-with-ubuntu-20-04-100e787105ad

- name: Installation de l'utilitaire des drivers propriétaires de Ubuntu
  package:
    name: ubuntu-drivers-common
    state: latest

- name: Affichage des drivers propriétaires recommendés
  command: ubuntu-drivers devices
  register: output
- debug:
    var: output.stdout_lines

- name: Installation des drivers propriétaires recommandés
  command: ubuntu-drivers install

- name: Installation de CUDA
  package:
    name: nvidia-cuda-toolkit
    state: latest

- name: Affichage de la version de CUDA
  command: nvcc --version
  register: output
- debug:
    var: output.stdout_lines
