# https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-programming-environment-on-an-ubuntu-20-04-server
# https://www.digitalocean.com/community/tutorials/how-to-install-tensorflow-on-ubuntu-20-04

- name: Installation des paquets
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - python3
    - python3-pip
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3-dev
    - python3-venv
