# https://towardsdatascience.com/set-up-of-a-personal-gpu-server-for-machine-learning-with-ubuntu-20-04-100e787105ad
# https://linoxide.com/how-to-install-nvidia-driver-on-ubuntu/

- name: Installation de l'utilitaire des drivers propriétaires de Ubuntu
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - hwinfo
    - ubuntu-drivers-common
    - nvidia-cuda-toolkit

- name: Copie du programme à compiler pour valider CUDA
  copy:
    src: hello.cu
    dest: /tmp/hello.cu

- name: Export des librairies dans la variable d'environnement $LD_LIBRARY_PATH
  blockinfile:
    # bashrc pour tous les utilisateurs
    path: /etc/bash.bashrc
    block: |
      export LD_LIBRARY_PATH=/usr/lib/cuda/include:$LD_LIBRARY_PATH
      export LD_LIBRARY_PATH=/usr/lib/cuda/lib64:$LD_LIBRARY_PATH
